name: check-migrations
on:
  pull_request:
    types:
      - opened
    branches: [ "main" ]
    paths:
      - 'migrations/**.js'
jobs:
  check-migrations:
    runs-on: ubuntu-latest
    env:
      TEST_DB_DATABASE: testdb
      TEST_DB_USER: root
      TEST_DB_PASSWORD: root
    steps:
      - run: sudo systemctl start mysql.service
      - run: sudo mysql -e 'CREATE DATABASE ${{env.TEST_DB_DATABASE}};' -u ${{env.TEST_DB_USER}} -p${{env.TEST_DB_PASSWORD}}
      - run: sudo mysql -e 'SHOW DATABASES;'  -u ${{env.TEST_DB_USER}} -p${{env.TEST_DB_PASSWORD}}
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
      - uses: actions/checkout@v3
      - run: pwd
      - run: npm install db-migrate -g
      - run: npm install -g db-migrate-mysql
      - run: db-migrate up -e test