name: learn-github-actions
on:
  pull_request:
    types:
      - opened
    branches: [ "main" ]
    # branches:    
    #   - 'releases/**'
    # paths:
    #   - '**.js'
jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: git status
      - uses: actions/setup-node@v3
        with:
          node-version: '14'